name: tcr-ros2-talker-listener
version: '0.1'
summary: ROS 2 Talker/Listener Example
description: |
 This example launches a ROS 2 talker and listener.
 
license: AGPL-1.0-only

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode
base: core20

architectures:
  - arm64

parts:
 ros-demos:
   plugin: colcon
   source: https://github.com/ros2/demos.git
   source-branch: foxy
   source-subdir: demo_nodes_cpp
   stage-packages: [ros-humble-ros2launch]

apps:
 ros2-talker-listener:
   command: opt/ros/humble/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
   plugs: [network, network-bind]
   extensions: [ros2-humble]
